### PR TITLE
Add DrmagicE as reviewer of OpenYurt

### PR DESCRIPTION
**Pull request by DrmagicE**
## GitHub Username

@DrmagicE 
## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch 
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
#513 
#510 
#509 
#495 
#483 
#381 
#222 
#218 
#205
- Issues :
#527
#450
#376
#504
#476
#212

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@DrmagicE welcome you to apply OpenYurt reviewer. agree +1

**Comment by adamzhoul** [comment]
agree +1

**Comment by qclc** [comment]
agree +1

**Comment by Peeknut** [comment]
agree +1

**Comment by SataQiu** [comment]
+1

**Review by SataQiu — APPROVED** [review]
LGTM

**Comment by rambohe-ch** [comment]
@DrmagicE Congratulations to you as reviewer, and you can check the reviewer's responsibilities and privileges here: https://github.com/openyurtio/community/blob/main/community-membership.md#reviewer

**Pull request merged**
