### PR TITLE
beta.kubernetes.io is deprecated, use kubernetes.io instead

### PR DESCRIPTION
**Pull request by fujitatomoya**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

deprecated resource should not be used to avoid warning.

#### Which issue(s) this PR fixes:

avoid the following deprecation warning.

```bash
root@tomoyafujita:~/openyurt# kubectl apply -f config/setup/yurt-tunnel-server.yaml
clusterrole.rbac.authorization.k8s.io/tunnel-proxy-client created
clusterrolebinding.rbac.authorization.k8s.io/tunnel-proxy-client created
clusterrole.rbac.authorization.k8s.io/yurt-tunnel-server created
clusterrolebinding.rbac.authorization.k8s.io/yurt-tunnel-server created
serviceaccount/yurt-tunnel-server created
service/x-tunnel-server-svc created
service/x-tunnel-server-internal-svc created
configmap/yurt-tunnel-server-cfg created
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/arch]: deprecated since v1.14; use "kubernetes.io/arch" instead
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
deployment.apps/yurt-tunnel-server created
```

#### Special notes for your reviewer:

N.A

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Comment by Congrool** [comment]
We have @zhaodiaoer working on #958, so we can discuss there.
Thanks for your contribution.

**Comment by rambohe-ch** [comment]
@fujitatomoya Thank you for posting pull request to replace `beta.kubernetes.io` labels. Frankly speaking, pull request #958 is also targeted to replace these labels, but #958 is not merged because the corresponding helm charts([yurt-tunnel-server](https://github.com/openyurtio/openyurt/blob/master/charts/openyurt/templates/yurt-tunnel-server.yaml) and [yurt-tunnel-agent](https://github.com/openyurtio/openyurt/blob/master/charts/openyurt/templates/yurt-tunnel-agent.yaml)) are not updated.

meanwhile, the owner of #958 have no response for nearly a week. so how about fix the helm charts ``beta.kubernetes.io` labels instead of `config/setup/yurt-tunnel-server.yaml` in your pull request?

**Comment by fujitatomoya** [comment]
@rambohe-ch thanks for the quick response, will try that in this week.

**Comment by fujitatomoya** [comment]
@rambohe-ch see https://github.com/openyurtio/openyurt/pull/969/commits/2be849b7783f7445575cceb28b736e35dcc56474

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
