### PR TITLE
proposal of yurthub cache refactoring

### PR DESCRIPTION
**Pull request by Congrool**
#### What type of PR is this?
/kind documentation
/kind design
/sig storage

#### What this PR does / why we need it:

When implementing the feature of pool-coordinator, I encountered serval problems to be solved first. So, it is this pr. Details are in the proposal.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@Congrool Maybe we should also consider the interface for reading objects from yurthub cache?

**Comment by rambohe-ch** [comment]
> @rambohe-ch Currently we have Get/List/ListKeys only for reading objects in diskStorage. In the case of Pool-Coordiantor, the read request will be send to the APIServer in pool-coordinator, so it does not need to use the read interface to read object from cache directly.

@Congrool  ok, i think pool-coordinator will not implement Get/List/ListKeys funcs for Storage interface because yurthub read from kube-apiserver of pool-coordinator directly.

**Comment by Congrool** [comment]
need revision
/hold

**Review by rambohe-ch — APPROVED** [review]

**Comment by Congrool** [comment]
revised according to the newest implementation

**Comment by rambohe-ch** [comment]
@Congrool how about the definition of `KeyBuildInfo` and `Key` struct?

**Comment by Congrool** [comment]
The definition of Key is like:
```go
type Key interface {
	Key() string
}

type KeyBuildInfo struct {
	Component string
	Namespace string
	Name      string
	Resources string
	Group     string
	Version   string
}
```

I'll update it in this proposal.

**Comment by Congrool** [comment]
proposal is updated with definition of Key and new interface names

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
