### PR TITLE
add proposal to unify cloud edge comms solution

### PR DESCRIPTION
**Pull request by zzguang**
Current OpenYurt provides 2 independent solutions in cloud edge comms domain, which are Raven and YurtTunnel, this proposal aims to integrate YurtTunnel into Raven, and provide an unified cloud edge comms solution to users.

Signed-off-by: zzguang <zhengguang.zhang@intel.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@zzguang please fix misspell errors.

**Comment by rambohe-ch** [comment]
@zzguang Thanks for posting pull request about integrating yurttunnel into raven. and i agree with you that yurttunnel and raven are independent solutions in cloud edge comms domain. but yurttunnel is a 7 layer solution for forwarding http/https requests from cloud to edge, and raven is a 3 layer solution for forwarding requests between cloud and edge, or edge to edge. 

DevOps traffic and business data traffic can use these two solutions simultaneously in terms of their requirements. for example, DevOps traffic can use both yurttunnel and raven.

I think that the solution 4 is so complicated because end user should take care 4 components. how about integrate raven-gateway-agent and raven-tunnel-agent into one component?

**Comment by zzguang** [comment]
> @zzguang Thanks for posting pull request about integrating yurttunnel into raven. and i agree with you that yurttunnel and raven are independent solutions in cloud edge comms domain. but yurttunnel is a 7 layer solution for forwarding http/https requests from cloud to edge, and raven is a 3 layer solution for forwarding requests between cloud and edge, or edge to edge.
> 
> DevOps traffic and business data traffic can use these two solutions simultaneously in terms of their requirements. for example, DevOps traffic can use both yurttunnel and raven.
> 
> I think that the solution 4 is so complicated because end user should take care 4 components. how about integrate raven-gateway-agent and raven-tunnel-agent into one component?

Thanks for your comments, IMHO, since we can not merge the layer 7 yurttunnel completely into layer 3 raven, we should decouple them clearly for users. If we fuse them on edge side while keep them separated on cloud side, it may lead to confusions to users when they only want to adopt one of them.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
