### PR TITLE
Add released openyurt versions to projectInfo when building binaries

### PR DESCRIPTION
**Pull request by Congrool**
#### What type of PR is this?
/kind enhancement

#### What this PR does / why we need it:
As #1007 , when we release new version of openyurt, we have to manually revise versions in code, which is often forgot. This pr will automatically detect released versions of openyurt and link to projectInfo when building binaries, which can simplify what we need to do when releasing new version.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by Congrool** [comment]
We can build yurtctl and run `yurtctl --version` to check this pr.
```paintext
$ _output/local/bin/linux/amd64/yurtctl --version
yurtctl version: projectinfo.Info{GitVersion:"v1.0.0", GitCommit:"e4eb566", BuildDate:"2022-09-22T08:50:38Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64", AllVersions:[]string{"v0.1.0-beta.1", "v0.2.0", "v0.3.0", "v0.4.0", "v0.4.1", "v0.5.0", "v0.6.0", "v0.6.1", "v0.7.0", "v0.7.1", "v1.0.0", "v1.0.0-rc1"}}
```

**Comment by rambohe-ch** [comment]
> We can build yurtctl and run `yurtctl --version` to check this pr.
> 
> ```
> $ _output/local/bin/linux/amd64/yurtctl --version
> yurtctl version: projectinfo.Info{GitVersion:"v1.0.0", GitCommit:"e4eb566", BuildDate:"2022-09-22T08:50:38Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64", AllVersions:[]string{"v0.1.0-beta.1", "v0.2.0", "v0.3.0", "v0.4.0", "v0.4.1", "v0.5.0", "v0.6.0", "v0.6.1", "v0.7.0", "v0.7.1", "v1.0.0", "v1.0.0-rc1"}}
> ```

@Congrool It's a good idea to detect and verify version of OpenYurt automatically. and one of my concerns is that `AllVersions` string will become longer and longer, so how about left the latest 5 versions?

**Comment by Congrool** [comment]
@rambohe-ch Good idea, I'll do that. I think the number of valid openyurt versions should depend on how many versions we will keep maintain and do back-port.

**Comment by rambohe-ch** [comment]
> @rambohe-ch Good idea, I'll do that. I think the number of valid openyurt versions should depend on how many versions we will keep maintain and do back-port.

@Congrool I think maybe 3 or 4 versions is enough.

**Comment by Congrool** [comment]
Done. And currently I set the num as 3, which means, for example, v1.0.\*, v0.7.\* and v0.6.\*. The linked versions looks like:
```plain-text
$ _output/local/bin/linux/amd64/yurtctl --version
yurtctl version: projectinfo.Info{GitVersion:"v1.0.0", GitCommit:"9d4c80e", BuildDate:"2022-09-23T11:28:30Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64", AllVersions:[]string{"v1.0.0-rc1", "v1.0.0", "v0.7.0", "v0.7.1", "v0.6.0", "v0.6.1"}}
```

PTAL @rambohe-ch

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
