### PR TITLE
Fix: update package dependencies

### PR DESCRIPTION
**Pull request by fengshunli**
update GHSA-vvpx-j8f3-3w6h and upgrade thought about dependencies

### CODE REVIEW

**Comment by fengshunli** [comment]
update GHSA-vvpx-j8f3-3w6h and upgrade thought about dependencies

**Comment by Congrool** [comment]
I saw that `golang.org/x/net@v0.7.0` is invulnerable to such security problem. Did you use `go get -u golang.org/x/net@v0.7.0` to upgrade it? 

I find it seems to contain more changes than using `go get -u golang.org/x/net@v0.7.0` .

**Comment by fengshunli** [comment]
Directly modify the  golang.org/x/net version of go.mod

**Comment by Congrool** [comment]
Well, here's my result
```diff
	go.uber.org/atomic v1.9.0 // indirect
	go.uber.org/multierr v1.6.0 // indirect
	go.uber.org/zap v1.19.0 // indirect
	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 // indirect
-	golang.org/x/net v0.0.0-20220225172249-27dd8689420f // indirect
+	golang.org/x/net v0.7.0 // indirect
	golang.org/x/oauth2 v0.0.0-20220223155221-ee480838109b // indirect
	golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f // indirect
-	golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
-	golang.org/x/text v0.3.7 // indirect
+	golang.org/x/term v0.5.0 // indirect
+	golang.org/x/text v0.7.0 // indirect
	golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac // indirect
```

It seems not introduce so many changes.

**Comment by fengshunli** [comment]
Update the cve vulnerabilities of these dependent packages
image

**Review by Congrool — COMMENTED** [review]
/lgtm

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
