### PR TITLE
Add DrmagicE as maintainer of OpenYurt

### PR DESCRIPTION
**Pull request by DrmagicE**
## GitHub Username

@DrmagicE 
## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch 
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
#513 
#510 
#509 
#495 
#483 
#381 
#222 
#218 
#205
- Issues :
#527
#450
#376
#504
#476
#212

### CODE REVIEW

**Comment by Fei-Guo** [comment]
+ Thanks a lot for your contribution.

**Comment by rambohe-ch** [comment]
I agree with @DrmagicE to be maintainer of OpenYurt. 
and my considerations are:
1. He have made a lot of contribution to OpenYurt community, and familiar with OpenYurt.
2. Now he is  responsible for designing cloud-edge, edge-edge communication solutions across the public network, and edge container network solution is a key feature for OpenYurt community.
3. OpenYurt is using by the company(China Telecom) that @DrmagicE is working, It's a good end user case.

**Comment by rambohe-ch** [comment]
@Fei-Guo @yixingjia @charleszheng44

**Comment by charleszheng44** [comment]
+1

**Pull request merged**
