### PR TITLE
change access permission to default in general.

### PR DESCRIPTION
**Pull request by fujitatomoya**
backport of #1576 for release-v1.0

#### What type of PR is this?

/kind bug

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
lgtm, requesting maintainer review.

**Review by YTGhost — COMMENTED** [review]
/lgtm

**Comment by fujitatomoya** [comment]
https://sonarcloud.io/project/issues?id=openyurtio_openyurt&pullRequest=1599&resolved=false&types=CODE_SMELL is unrelated.

@rambohe-ch friendly ping.

**Comment by fujitatomoya** [comment]
@YTGhost @rambohe-ch 

when this branch is synced with tag `v1.1.0` ? that is the version tag we detected this problem? i am not really familiar with release procedure, could you share the thought?

**Comment by YTGhost** [comment]
> @YTGhost @rambohe-ch
> 
> when this branch is synced with tag `v1.1.0` ? that is the version tag we detected this problem? i am not really familiar with release procedure, could you share the thought?

@fujitatomoya we have a new tag `v1.1.1`, see: https://github.com/openyurtio/openyurt/releases/tag/v1.1.1

**Pull request merged**
