### PR TITLE
Add lwmqwer as maintainer of OpenYurt

### PR DESCRIPTION
**Pull request by lwmqwer**
## GitHub Username
 
 @lwmqwer
 ## Organization you are requesting membership in
 
 openyurtio
 ## Sponsors
 
 @rambohe-ch
 ## Requirements
 
* [x]   I have joined in the community [Dingding] and [WeChat]
* [x]   I often attend Openyurt Community Week
* [x]   I have reviewed the [community membership docs]
* [x]   I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
* [x]   I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
* [x]   I am actively contributing to 1 or more OpenYurt subprojects
 
 
 ## List of your contributions
 
* Subproject: 
   [Yurt-edgex-controller](https://github.com/openyurtio/yurt-edgex-manager)

* Issues:
#521

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@lwmqwer Would you be able to reference this example(https://github.com/openyurtio/openyurt/pull/589) to update you apply message?

**Comment by lwmqwer** [comment]
> 
> 
> @lwmqwer Would you be able to reference this example(#589) to update you apply message?

Done

**Comment by rambohe-ch** [comment]
@lwmqwer welcome you to apply maintainer of OpenYurt, agree +1

**Comment by rambohe-ch** [comment]
@Fei-Guo @yixingjia @charleszheng44 @qclc @gnunu @DrmagicE @SataQiu

**Comment by qclc** [comment]
agree + 1

**Comment by DrmagicE** [comment]
agree + 1

**Comment by Fei-Guo** [comment]
+1

**Comment by charleszheng44** [comment]
:+1

**Pull request merged**
