### PR TITLE
Add qclc as maintainer of OpenYurt

### PR DESCRIPTION
**Pull request by qclc**
## GitHub Username

@qclc 

## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 

- PRs reviewed / authored:
  https://github.com/openyurtio/openyurt/pull/225
  https://github.com/openyurtio/openyurt/pull/244
  https://github.com/openyurtio/openyurt/pull/326
  https://github.com/openyurtio/openyurt/pull/359
  https://github.com/openyurtio/openyurt/pull/369
  https://github.com/openyurtio/openyurt/pull/554
  https://github.com/openyurtio/yurt-device-controller/pull/1
  https://github.com/openyurtio/yurt-device-controller/pull/2
  https://github.com/openyurtio/yurt-device-controller/pull/4
  https://github.com/openyurtio/yurt-device-controller/pull/5
  https://github.com/openyurtio/yurt-device-controller/pull/6
  https://github.com/openyurtio/yurt-device-controller/pull/8
  https://github.com/openyurtio/yurt-device-controller/pull/11
  https://github.com/openyurtio/yurt-device-controller/pull/12

- Issues :
  https://github.com/openyurtio/openyurt/issues/162
  https://github.com/openyurtio/openyurt/issues/281
  https://github.com/openyurtio/openyurt/issues/325
  https://github.com/openyurtio/openyurt/issues/573

### CODE REVIEW

**Comment by rambohe-ch** [comment]
I agree with @qclc to apply Maintainer of OpenYurt community, and my considerations are:
1. He had made a lot of contributions to community. and familiar with OpenYurt.
2. He has owned and pushed EdgeX integrated with OpenYurt, and implement cloud-native IOT solution. you can reference the repo: https://github.com/openyurtio/yurt-device-controller

**Comment by rambohe-ch** [comment]
@Fei-Guo @yixingjia @charleszheng44

**Comment by Fei-Guo** [comment]
+1

**Comment by charleszheng44** [comment]
+1

**Comment by SataQiu** [comment]
+1

**Review by SataQiu — COMMENTED** [review]
LGTM

**Pull request merged**
