### PR TITLE
feat: remove yurtadm init command

### LINKED ISSUE #1535: [feature request] Remove yurtadm init command
**What would you like to be added**:
Remove `yurtadm init` command.

**Why is this needed**:
Since the `yurtadm init` command is no longer maintained and have some problem, it needs to be removed in order not to confuse yurtadm users.

**others**
/kind feature

### PR DESCRIPTION
**Pull request by YTGhost**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #1535

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by rambohe-ch — APPROVED** [review]

**Comment by rambohe-ch** [comment]
@YTGhost How about make a pull request to update `yurtadm` docs in the homepage website?

**Comment by YTGhost** [comment]
> @YTGhost How about make a pull request to update `yurtadm` docs in the homepage website?

Sure

**Comment by YTGhost** [comment]
> @YTGhost How about make a pull request to update `yurtadm` docs in the homepage website?

Here: https://github.com/openyurtio/openyurt.io/pull/325

**Pull request merged**
