### PR TITLE
build: added github registry

### LINKED ISSUE #1575: Consider github container registry
Please consider moving away from docker hub do github container registry (https://github.com/features/packages#pricing)
Pricing is free for public repositories. 
The problem is, that docker has very limited rate limits (https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=Docker%20Hub%20limits%20the%20number,pulls%20per%206%20hour%20period.)

/kind feature

### PR DESCRIPTION
**Pull request by siredmar**
#### What type of PR is this?
/kind enhancement
#### What this PR does / why we need it:
Adds support for pushing to github container registry to avoid docker hub rate limits. 

#### Which issue(s) this PR fixes:

Fixes #1575 

#### Does this PR introduce a user-facing change?

```release-note
OCI images can now also be found on Github
```

### CODE REVIEW

**Comment by siredmar** [comment]
@rambohe-ch you need to provide two repository secrets called 
`GITHUB_REGISTRY_USERNAME` and `GITHUB_REGISTRY_USERNAME` containing the username that pushes and a PAT (private access token) from github described in the following docs: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by rambohe-ch** [comment]
> @rambohe-ch you need to provide two repository secrets called `GITHUB_REGISTRY_USERNAME` and `GITHUB_REGISTRY_USERNAME` containing the username that pushes and a PAT (private access token) from github described in the following docs: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

@siredmar Very appreciate for your pull request.  Because secrets are allowed start with `GITHUB_`, so i have created two secrets named as `GH_REGISTRY_USERNAME` and `GH_REGISTRY_PASSWORD`, please update your pull request with these two secrets.

**Comment by rambohe-ch** [comment]
@siredmar please fix the conflicting files. and the changes in this pull request should be merged into `registry.yaml`.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
