### PR TITLE
invalid doc link

### PR DESCRIPTION
**Pull request by lilongfeng0902**
/kind documentation

#### What this PR does / why we need it:
yurt-app-manager repository does not exist, it has been added openyurt repository.
#### Which issue(s) this PR fixes:

Fixes #
None
#### Does this PR introduce a user-facing change?

```release-note

```
NONE
#### other Note

NONE

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@lilongfeng0902 I think we can remove `cmd/yurt-app-manager` in OpenYurt. would you like to update this pr?

**Comment by lilongfeng0902** [comment]
> @lilongfeng0902 I think we can remove `cmd/yurt-app-manager` in OpenYurt. would you like to update this pr?

I have removed `cmd/yurt-app-manager` in OpenYurt. Please review again, thanks.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
