### PR TITLE
pull yurt-tunnel-server image when IfNotPresent

### LINKED ISSUE #511: [BUG]Avoid using different version of yurt-tunnel-agent and yurt-tunnel-server, when deploying with yurtctl
When deploying yurt-tunnel with yurtctl, we will set `imagePullPolicy: IfNotPresent` for [yurt-tunnel-agent](https://github.com/openyurtio/openyurt/blob/master/pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go#L49) and `imagePullPolicy: Always` for [yurt-tunnel-server](https://github.com/openyurtio/openyurt/blob/master/pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go#201). It possibly makes users use local old version of yurt-tunnel-agent and the latest version of yurt-tunnel-server which may cause potential problems.  

I think it's better to set same `imagePullPolicy` for yurt-tunnel-agent and yurt-tunnel-server.

/kind bug

### PR DESCRIPTION
**Pull request by Congrool**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
To avoid using different version of yurt-tunnel-agent and yurt-tunnel-server.

#### Which issue(s) this PR fixes:

Fixes #511 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@Congrool how about update `imagePullPolicy` of `config/setup/yurt-tunnel-server.yaml` and `config/yaml-template/yurt-tunnel-server.yaml`?

**Comment by Congrool** [comment]
> @Congrool how about update `imagePullPolicy` of `config/setup/yurt-tunnel-server.yaml` and `config/yaml-template/yurt-tunnel-server.yaml` at the same time?

Sure, I'll do it.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
