### PR TITLE
【FIX】Update service topology for k8s 1.21 and unit test

### PR DESCRIPTION
**Pull request by JameKeal**
#### What this PR does / why we need it:
The service takes effect in the new version

#### Which issue(s) this PR fixes:
[https://github.com/openyurtio/openyurt/issues/789](https://github.com/openyurtio/openyurt/pull/url)

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@JameKeal Adapt service topology for K8s v1.21.x, but k8s libraries version in go.mod are updated to v1.22.3, I think if we update go.mod in this pull request, maybe other features could not work.

**Comment by JameKeal** [comment]
> @JameKeal Adapt service topology for K8s v1.21.x, but k8s libraries version in go.mod are updated to v1.22.3, I think if we update go.mod in this pull request, maybe other features could not work.

By your means, if I don't update go.mod, someone who pull the master branch to build code, it's also fail.

If you think it's not a problem, I can recover the go.mod.

**Comment by Congrool** [comment]
I think we can merge #821 before this pr, at that time, everything will be ok.

**Comment by rambohe-ch** [comment]
Fixes #789

**Comment by rambohe-ch** [comment]
@JameKeal please rebase the newest master branch.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
