### PR TITLE
cherry-pick yurthub code of pool-coordinator-dev

### PR DESCRIPTION
**Pull request by Congrool**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Yurthub part of pool-coordinator implementation.

Functions of these code refer to: #778, #779

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

These code is cherry-picked from pool-coordinator-dev, which contains

|PR|commit|Note|
|-|-|-|
|#1035 | 0db2b8749013b1e9ff2522a49790da60e0e22cff ||
|#1073| 61b6716e856aeb88528060eb4ef9984c14b3678b||
|#1103| f500dad2af892084129ca2b9687a1a04db95e3cb||
|#1125| 78cdc6206d59b161f5ae3fda42719d3a03f9b699||
|#1131| a5cd6e33086e7e1311486ea180218d146e85d7b2||
|#1134| f77c971fa6f4fd93f8ca649e1cf6ddf05601f7da||
|#1126| 07fc159dd2d126e2b60b6dd17b5936f1251704a2||
|#1137| 7fb43e70f8c59e87c906ddcad2fb5db8f52d9f72||
|#1138| 145705333871aa058d9adbc113a36aab020e01e4||
|#1139| b4a47b9dcdd7f755f2a94683044c2bfa4ca70568||
|#1140| 7964a5ce8bdfeecbe4fac9f2ed1fc44079f406b6||
|#1141| 81aa62b245b63157a0f887d594d5d0d4965f393a|Partial Pick|
|#1142| 094a27351017f7f5ba97de74c87fa30da76c53bb||
|#1144| d02dac7b7d272822f03e523354e7042a9b21c05a||
|#1145| abf81f373cf6bdd6f20cf60d4b756ceb7c05e64f|Partial Pick|
|#1147| 9c0df52a050cd79edf2bf643d78f1a91149b5ccd||
|#1148| 803e23312e544242177b2cd2a8b6a752ffcdf580|Partial Pick|
|#1153| 1d558ba00341ba0bbd22f124d0633058bc4ffc78||

Note: 
`Partial Pick` means this pr contains other code besides yurthub component.  The code of yurthub part was picked, and other code were not picked in this PR.

### CODE REVIEW

**Comment by Congrool** [comment]
/hold

Waiting for CI pass

**Comment by Congrool** [comment]
I think it's better to use `merge` instead of `squash and merge`. `squash and merge` will make us cannot distinguish code change among each commit, which may make the code hard to maintain.

**Review by rambohe-ch — APPROVED** [review]

**Comment by rambohe-ch** [comment]
Fixes #779

**Pull request merged**
