### PR TITLE
Add SataQiu as a maintainer of OpenYurt

### PR DESCRIPTION
**Pull request by SataQiu**
## GitHub Username
@SataQiu

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
#518 
#507 
#482 
#471 
#468 
#452 
#451 
#429 
#406 
#378 
#294 
#290 
#287 
#283 
#282 
#270 
#202 

- Issues :
#526 
#524 
#508 
#432 
#426 
#377 

## Brief Introduction

I actively use `OpenYurt` in our product, contribute `OpenYurt` to solve the problems encountered in the process of use. 
I am the main owner of the `openyurtio/yurtcluster-operator` project, and I am pushing to create the `OpenYurt` cluster in a declarative way.

### CODE REVIEW

**Comment by charleszheng44** [comment]
+1

**Comment by rambohe-ch** [comment]
@SataQiu welcome you to apply maintainer of OpenYurt. agree +1

**Comment by rambohe-ch** [comment]
@Fei-Guo @yixingjia

**Comment by Fei-Guo** [comment]
+1

**Pull request merged**
