### PR TITLE
add rerun failed workflows script

### PR DESCRIPTION
**Pull request by rambohe-ch**
/kind enhancement

#### What this PR does / why we need it:
reviewers or higher member can comment `/rerun` to trigger github actions that will rerun all failed workflows of the pull request.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
Fixes #1785

**Comment by JameKeal** [comment]
> /rerun

rerun seems not to run again? The e2e-tests is not working.

**Comment by rambohe-ch** [comment]
> > /rerun
> 
> rerun seems not to run again? The e2e-tests is not working.
> 
> Or that it can work after merge it.

@JameKeal @YTGhost Yes, it seems this script can work after merged.

**Review by YTGhost — APPROVED** [review]
/lgtm

**Pull request merged**
