### PR TITLE
fix: yurt-iot-dock cannot be dynamically deployed in platformadmin

### PR DESCRIPTION
**Pull request by LavenderQAQ**
#### What type of PR is this?
/kind bug
/sig iot

#### What this PR does / why we need it:
Because the `yurt-iot-dock` is an internal component of `openyurt` and is not in the standard configuration collected by the `auto-collector`, a separate decision for the `yurt-iot-dock` is added when calculating the required components.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by Rui-Gan — CHANGES_REQUESTED** [review]
We can remove the newYurtIoTDockComponent logic from initFramework as it is somewhat redundant.

**Review by Rui-Gan — APPROVED** [review]

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
