### PR TITLE
fix(yurt-manager): raven controller can't list calico blockaffinity

### PR DESCRIPTION
**Pull request by luckymrwang**
/kind bug

#### What this PR does / why we need it:
The CR `blockaffinity` is defined as `projectcalico.org/v3` in the new calico api package, but in fact calico use `crd.projectcalico.org/v1` version.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by fighterhit** [comment]
hi @luckymrwang , thanks for your work! I met the same issue, has this PR completely fixed this problem?

**Comment by luckymrwang** [comment]
> hi @luckymrwang , thanks for your work! I met the same issue, has this PR completely fixed this problem?

Yes.

**Comment by fighterhit** [comment]
Hi @luckymrwang , I use your branch but `yurt-manager` report another error.
```
E0915 08:02:30.248561       1 deleg.go:144] setup "msg"="unable to setup controllers" "error"="no matches for raven.openyurt.io/v1beta1, Resource=gateways"
```

**Comment by luckymrwang** [comment]
> Hi @luckymrwang , I use your branch but `yurt-manager` report another error.
> 
> ```
> E0915 08:02:30.248561       1 deleg.go:144] setup "msg"="unable to setup controllers" "error"="no matches for raven.openyurt.io/v1beta1, Resource=gateways"
> ```

Because I fix it on the lastest `main` branch which is not stable version. If you want use it immediately, you can replace the `yurt-manager` image by [luckymrwang/yurt-manager:hotfix-v1.3.4](https://hub.docker.com/r/luckymrwang/yurt-manager) which I fixed it on the stable version `v1.3.4`.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
