### PR TITLE
[bugfix] detect unannotated tags when initilizing GIT_VERSION

### PR DESCRIPTION
**Pull request by Congrool**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In current master branch of openyurt, the command `git describe --abbrev=0` will initilize `GIT_VERSION` as `v0.5.0`, because it is the latest annotated tag and `v0.6.0` is not an annotated tag. Using the option of `--tags` will make `git describe` get the latest tag even it is unannotated.

The description of `--tags` option in the `git describe -h`: 
```
--tags                use any tag, even unannotated
```

We can check if a tag is an annotated tag through command `git for-each-ref refs/tags`. An unannotated tag will be marked as `commit`.
```
$ git for-each-ref refs/tags
2abb8ad93848adb2a11244373c01bd79d713eb38 commit refs/tags/v0.1.0-beta.1
9d0ae1b2aff825ff5efcde728e143e431cce8246 tag    refs/tags/v0.2.0
1ece6ab01a006b3fd6b6cd0e48dd6f33f95e4ed1 tag    refs/tags/v0.3.0
050a2d77d7b87c67bf5b2c3509505ec4a5008bca tag    refs/tags/v0.4.0
f19e66343e354dbf829ab0a277207a59ba31b902 commit refs/tags/v0.4.1
1a4933e345da9c5ed696e420698aac44c2fc343c tag    refs/tags/v0.5.0
7df5fd6a019e28ee4147a4b271f7ada91e6372a9 commit refs/tags/v0.6.0
d6f7f4866221e6df098996d0916a09022039042d commit refs/tags/v0.6.1
```

Why isn't it `v0.6.1` ?
I read some documention of git, and found that the command `git describe --abbrev=0 --tags` will only describe the lastest tag in the current branch. In other words, it will find the latest tag before the commit pointed by `HEAD`. `v0.6.1` is at a detachd `HEAD`, thus it will not be found by using `git describe` at the master branch.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by rambohe-ch — APPROVED** [review]

**Comment by Congrool** [comment]
It seems that the failure of CI is the result of network timeout. 
Could you please retest it? @rambohe-ch

**Comment by gnunu** [comment]
try:
git describe --tags `git rev-list --tags --max-count=1`

this can get tags across all branches, not just the current branch.

this can get us 0.6.1
:)

**Comment by rambohe-ch** [comment]
> try:
> 
> ```
> git describe --tags `git rev-list --tags --max-count=1`
> ```
> 
> this can get tags across all branches, not just the current branch.
> 
> this can get us 0.6.1 :)

@gnunu we should get latest tag of master branch, so `git describe --abbrev=0 --tags` is ok.
and i will merge this pr.

**Comment by Congrool** [comment]
> 

Wow, it works.  Thanks a lot.
But it's strange if we use tag `v0.6.1`, because we update new features to v0.6.0(the master branch). So here I think we can just use
```
git describe --abbrev=0 --tags
```

**Comment by gnunu** [comment]
> > try:
> > ```
> > git describe --tags `git rev-list --tags --max-count=1`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this can get tags across all branches, not just the current branch.
> > this can get us 0.6.1 :)
> 
> @gnunu we should get latest tag of master branch, so `git describe --abbrev=0 --tags` is ok. and i will merge this pr.

OK.

**Comment by LindaYu17** [comment]
a quick question, why not rebase v0.6.1 to master (git rebase v0.6.1 master)? @rambohe-ch

**Comment by rambohe-ch** [comment]
> a quick question, why not rebase v0.6.1 to master (git rebase v0.6.1 master)? @rambohe-ch

@LindaYu17 only a part of commits in master branch will be added to branch release-v0.6, and tag v0.6.1 is released based on the branch rlease-v0.6.

**Review by rambohe-ch — COMMENTED** [review]
LGTM

**Pull request merged**
