### PR TITLE
bugfix: even no endpoints left after filter, an empty object should be returned to clients

### PR DESCRIPTION
**Pull request by rambohe-ch**
/kind bug

#### What this PR does / why we need it:
if no endpoints left after service topology filtering, yurthub should return a empty endpointslice to clients(like kube-proxy) instead of skipping the object. because kube-proxy need to use the empty endpointslice to update network setting on edge nodes.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@zzguang @yingjianjian PTAL

**Review by Congrool — COMMENTED** [review]
/lgtm

**Pull request merged**
