### PR TITLE
use https[s] proxy in docker for release build if necessary

### PR DESCRIPTION
**Pull request by gnunu**
/kind bug

#### What this PR does / why we need it:
When build release from a proxy env, http[s]_proxy is needed within the build container.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/assign @rambohe-ch 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@gnunu would you be able to add examples how to use these two new envs?

**Comment by gnunu** [comment]
> @gnunu would you be able to add examples how to use these two new envs?

in environment behind proxy like our company, normally these env's would be set:
http_proxy=http://XXXX:PPP
https_proxy=https://XXXX:PPP

in building docker container, these env's are also needed for network access.

if no proxy is needed (no env's set), then nothing to worry due to [[ -n ${http_proxy+x} ]] guard.

**Pull request merged**
