### PR TITLE
Update init.go

### PR DESCRIPTION
**Pull request by guoguodan**
add condition: len(s)==2

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@guoguodan very appreciate for your pull request. would you like to explain the reason why should improve the condition: `len(s)==2`?

**Comment by rambohe-ch** [comment]
@guoguodan by the way, the e2e test has failed because of version check.

**Comment by guoguodan** [comment]
@rambohe-ch Thinks for your reply. Overall context, the conditios is exists:len(s)<2 , len(s) >3 and len(s)==3 ,but leak the condition: len(s)==2

**Comment by rambohe-ch** [comment]
> @rambohe-ch Thinks for your reply. Overall context, the conditios is exists:len(s)<2 , len(s) >3 and len(s)==3 ,but leak the condition: len(s)==2

@guoguodan I think that len(s) == 2 should be true in the condition, like version: v1.22 is allowed to run a kind cluster.

**Pull request closed without merging**
