### PR TITLE
fix node autonomy annotation key

### PR DESCRIPTION
**Pull request by rambohe-ch**
/kind enhancement

#### What this PR does / why we need it:
fix node autonomy annotation key that use label prefix of project info

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### other Note

other docs that use this annotation key will be updated by another pull request.

### CODE REVIEW

**Comment by Peeknut** [comment]
The `AnnotationAutonomy` is used in another file: `pkg/yurtctl/constants/constants.go`.
It also needs to be modified.

**Comment by rambohe-ch** [comment]
> The `AnnotationAutonomy` is used in another file: `pkg/yurtctl/constants/constants.go`. It also needs to be modified.

@Peeknut Thank you for pointing out the problem.

**Comment by Peeknut** [comment]
As autonomy annotation key is used more than one place, how about define it in projectinfo and we can just use `GetAutonomyAnnotation()` ?

**Comment by rambohe-ch** [comment]
> As autonomy annotation key is used more than one place, how about define it in projectinfo and we can just use `GetAutonomyAnnotation()` ?

@Peeknut It's a good idea, I will add autonomy annotation key definition in ProjectInfo.

**Pull request merged**
