### PR TITLE
upgrade helm charts image version to v1.4.0

### LINKED ISSUE #1846: [BUG] [yurt-manager] Error: unknown flag: --leader-elect-resource-name
**What happened**:
Step 1. Installing yurt-manager refer to https://openyurt.io/zh/docs/installation/manually-setup#31-%E5%AE%89%E8%A3%85yurt-manager
Step 2. Exec `kubectl get pod -n kube-system | grep yurt-manager` and finds out yurt-manager's status is `CrashLoopBackOff`
Step 3. Get logs of yurt-manager and it says **Error: unknown flag: --leader-elect-resource-name**

**What you expected to happen**:
yurt-manager running successfully

**How to reproduce it (as minimally and precisely as possible)**:
Refer to **What happened**

**Anything else we need to know?**:
Here's the whole logs of yurt-manager:
```
root@ubuntu:/home/ubuntu# kubectl logs -p yurt-manager-5458c7c5b5-s2vcw -n kube-system
Error: unknown flag: --leader-elect-resource-name
Usage:
  yurt-manager [flags]

Generic flags:

      --controllers strings                    A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'. (default [*])
      --disable-independent-webhooks strings   A list of webhooks to disable. '*' disables all webhooks, 'foo' disables the webhook named 'foo'.
      --enable-leader-election                 Whether you need to enable leader election. (default true)
      --feature-gates mapStringBool            A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
                                               AllAlpha=true|false (ALPHA - default=false)
                                               AllBeta=true|false (BETA - default=false)
                                               RavenL7Proxy=true|false (ALPHA - default=false)
      --health-probe-addr string               The address the healthz/readyz endpoint binds to. (default ":10272")
      --metrics-addr string                    The address the metric endpoint binds to. (default ":10271")
      --rest-config-burst int                  rest-config-burst. (default 50)
      --rest-config-qps int                    rest-config-qps. (default 30)
      --version                                Print the version information, and then exit
      --webhook-port int                       The port on which to serve HTTPS for webhook server. It can't be switched off with 0 (default 10273)
      --working-namespace string               The namespace where the yurt-manager is working. (default "kube-system")

Nodepool controller flags:

      --create-default-pool   Create default cloud/edge pools if indicated.

Yurtstaticset controller flags:

      --node-servant-image string   Specify node servant pod image used for YurtStaticSet upgrade. (default "openyurt/node-servant:latest")

Global flags:

      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files
  -h, --help                             help for yurt-manager
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --one_output                       If true, only write logs to their native severity level (vs also writing to each lower severity level)
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity (default 0)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

**Environment**:
- OpenYurt version: 
- Kubernetes version (use `kubectl version`): v1.28.4
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 5.15.0-1043-raspi #46-Ubuntu SMP PREEMPT Mon Nov 13 15:08:58 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: helm
- Others:

**others**

/kind bug

### PR DESCRIPTION
**Pull request by YTGhost**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #1846 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by YTGhost** [comment]
@rambohe-ch PTAL

**Comment by rambohe-ch** [comment]
@YTGhost Thanks for posting a pull request, and please also update `version` in Chart.yaml.

- yurt-manager: 

version: 1.4.1 --> 1.4.2
https://github.com/openyurtio/openyurt/blob/master/charts/yurt-manager/Chart.yaml

- yurthub:

version: 1.4.0 --> v1.4.1
https://github.com/openyurtio/openyurt/blob/master/charts/yurthub/Chart.yaml

**Comment by YTGhost** [comment]
@rambohe-ch PTAL

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
