### PR TITLE
feat: support edgex minnesota through auto-collector

### LINKED ISSUE #1581: [feature request] support edgex minnesota through auto-collector
**What would you like to be added**:
Currently auto-collector has the edgex minnesota configuration, but the new version is on hold while we merge the code. After my manual review, I will propose a pr to merge it.

**Why is this needed**:
Support for the new version of edgex.

**others**
/kind feature

### PR DESCRIPTION
**Pull request by LavenderQAQ**
#### What type of PR is this?
/kind feature
/sig iot

#### What this PR does / why we need it:
support edgex minnesota through auto-collector

#### Which issue(s) this PR fixes:

Fixes #1581 

#### other Note

I'm just a porter representing the auto-collector🤣

### CODE REVIEW

**Comment by LavenderQAQ** [comment]
Hold on, this is an automatically generated configuration, we still need to do some reviews on this edgex version🧐.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
