### PR TITLE
fix: kustomize build yaml skipping blockaffinity

### LINKED ISSUE #1716: [BUG] Failure to make manifests after adding calico/v3 in apis
**What happened**:
The `make manifests` of the master branch generate _.yaml, which fails to execute.
```
/home/hanqi/openyurt/openyurt/bin/controller-gen "crd:crdVersions=v1,maxDescLen=1000" rbac:roleName=role webhook paths="./pkg/..." output:crd:artifacts:config=_output/manifest/auto_generate/crd output:rbac:artifacts:config=_output/manifest/auto_generate/rbac output:webhook:artifacts:config=_output/manifest/auto_generate/webhook
hack/make-rules/kustomize_to_chart.sh --crd _output/manifest/auto_generate/crd  --webhook _output/manifest/auto_generate/webhook --rbac _output/manifest/auto_generate/rbac --output _output/manifest/kustomize --chartDir charts/yurt-manager
[crd] apps.openyurt.io_nodepools.yaml is a yaml file, need to copy to kustomize dir
[crd] apps.openyurt.io_yurtappdaemons.yaml is a yaml file, need to copy to kustomize dir
[crd] apps.openyurt.io_yurtappoverriders.yaml is a yaml file, need to copy to kustomize dir
[crd] apps.openyurt.io_yurtappsets.yaml is a yaml file, need to copy to kustomize dir
[crd] apps.openyurt.io_yurtstaticsets.yaml is a yaml file, need to copy to kustomize dir
[crd] iot.openyurt.io_deviceprofiles.yaml is a yaml file, need to copy to kustomize dir
[crd] iot.openyurt.io_deviceservices.yaml is a yaml file, need to copy to kustomize dir
[crd] iot.openyurt.io_devices.yaml is a yaml file, need to copy to kustomize dir
[crd] iot.openyurt.io_platformadmins.yaml is a yaml file, need to copy to kustomize dir
[crd] raven.openyurt.io_gateways.yaml is a yaml file, need to copy to kustomize dir
[crd] _.yaml is a yaml file, need to copy to kustomize dir
Error: accumulating resources: accumulation err='accumulating resources from '_.yaml': missing metadata.name in object {{apiextensions.k8s.io/v1 CustomResourceDefinition} {{ } map[] map[controller-gen.kubebuilder.io/version:v0.7.0]}}': must build at directory: '/home/hanqi/openyurt/openyurt/_output/manifest/kustomize/crd/_.yaml': file is not directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_nodepools.apps.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_yurtstaticsets.apps.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_yurtappdaemons.apps.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_yurtappsets.apps.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_gateways.raven.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_platformadmins.iot.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_devices.iot.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_deviceservices.iot.openyurt.io.yaml': No such file or directory
mv: cannot stat '/home/hanqi/openyurt/openyurt/charts/yurt-manager/crds/apiextensions.k8s.io_v1_customresourcedefinition_deviceprofiles.iot.openyurt.io.yaml': No such file or directory
[rbac] role.yaml is a yaml file, need to copy to kustomize dir
[rbac] manifests.yaml is a yaml file, need to copy to kustomize dir
```
The controller-gen generates `_.yaml`, which may be related to `pkg/apis/calico/v3`.

**What you expected to happen**:
Successful execution `makes manifests`.

**How to reproduce it (as minimally and precisely as possible)**:
```shell
make manifests
```

**Anything else we need to know?**:
It seems that https://github.com/openyurtio/openyurt/pull/1676 is the cause of the problem. @luckymrwang Please help to confirm.

**Environment**:
- OpenYurt version: master

/kind bug

### PR DESCRIPTION
**Pull request by luckymrwang**
#### What this PR does / why we need it:
CRD blockaffinity does not need to be generated. So skip it.

#### Which issue(s) this PR fixes:

Fixes #1716

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by luckymrwang** [comment]
@rambohe-ch @LavenderQAQ

**Review by rambohe-ch — APPROVED** [review]

**Review by LavenderQAQ — APPROVED** [review]
/lgtm

**Pull request merged**
