### PR TITLE
using the kubeconfig flag in controller-runtime.

### PR DESCRIPTION
**Pull request by zyjhtangtang**
#### What this PR does / why we need it:

When yurt-manager specifies a kubeconfig and sets automountServiceAccountToken to false, yurt-manager will fail to start.

#### Does this PR introduce a user-facing change?
```none```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@zyjhtangtang It's a good idea to use kubeconfig parameter of controller-time.

**Comment by rambohe-ch** [comment]
@zyjhtangtang would you like to fix trivy scan errors in this pr?

**Comment by zyjhtangtang** [comment]
> @zyjhtangtang would you like to fix trivy scan errors in this pr?

OK

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
