### PR TITLE
Docs: add more nodes for --cloud-nodes

### PR DESCRIPTION
**Pull request by adamzhoul**
#### What this PR does / why we need it:

two points here:
1.  update description about convert.

 this update is for better understating.
 the command below is to convert with one node as a cloud node. same as the logic thought.

2. add a note, how to use "," to add more nodes for --cloud-nodes params

 this is useful when we deploy our openYurt cluster.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by adamzhoul** [comment]
/assign @yixingjia
please have a look.

**Comment by rambohe-ch** [comment]
@adamzhoul Very appreciate you for improving the document of OpenYurt. and welcome you to apply for OpenYurt community member. you can get apply example here: https://github.com/openyurtio/community/issues/23

**Comment by adamzhoul** [comment]
> @adamzhoul Very appreciate you for improving the document of OpenYurt. and welcome you to apply for OpenYurt community member. you can get apply example here: openyurtio/community#23

@rambohe-ch  thanks for your inviting. will do it soon.

**Pull request merged**
