### PR TITLE
clean redundant lint in makefile

### PR DESCRIPTION
**Pull request by Congrool**
#### What type of PR is this?
/kind clean

#### What this PR does / why we need it:
We have already had `vet` and `fmt` in [golangci-lint](https://github.com/openyurtio/openyurt/blob/master/.golangci.yaml#L42-L48). So we don't need to run them before running unit tests.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by rambohe-ch — APPROVED** [review]

**Comment by rambohe-ch** [comment]
> It seems that we can still merge pr even codecov failed. Is it what we expect? @rambohe-ch

@Congrool yes, I think we can decide to merge pull request manually because codecov data maybe influenced by doc modification on some occasions.

**Comment by Congrool** [comment]
@rambohe-ch Sounds good, but this failure may be confusing for contributors. We'd better make sure that codecov can succeed in most cases.

As described in #922, we can add threshold to codecov to tolerate some small coverage rate jitter.

>codecov data maybe influenced by doc

It seems that doc does not affect the codecov. We can verify it in #921 after #922 being merged.

**Comment by rambohe-ch** [comment]
> @rambohe-ch Sounds good, but this failure may be confusing for contributors. We'd better make sure that codecov can succeed in most cases.
> 
> As described in #922, we can add threshold to codecov to tolerate some small coverage rate jitter.
> 
> > codecov data maybe influenced by doc
> 
> It seems that doc does not affect the codecov. We can verify it in #921 after #922 being merged.

@Congrool yes, codecov is a great tool, it will give the detail test file that decrease the code test coverage.

**Pull request merged**
