### PR TITLE
improve yurtadm join command

### PR DESCRIPTION
**Pull request by rambohe-ch**
/kind enhancement

#### What this PR does / why we need it:
1. add a util func: IsNil for verifying the nil interface.
2. change caCertHashes type from sets.String to []string
3. move some util functions from yurtadm/util to pkg/util because yurthub will use these utils later.
4. add unit tests for token util.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@YTGhost PTAL

**Comment by YTGhost** [comment]
@rambohe-ch Please fix the ci error

**Pull request merged**
