### PR TITLE
Add SataQiu as a reviewer of openyurtio/openyurt

### PR DESCRIPTION
**Pull request by SataQiu**
## GitHub Username
@SataQiu

## Organization you are requesting membership in

openyurtio/openyurt

## Sponsors
@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
   #452
   #451
   #442
   #429
   #378
   #290
   #283
   #270
   #202

- Issues :
   #427
   #453
   

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@SataQiu Thanks for your contribution to OpenYurt. and i am happy to support you to apply openyurt community reviewer.
agree +1

**Comment by Peeknut** [comment]
agree +1

**Comment by yixingjia** [comment]
+1

**Comment by Fei-Guo** [comment]
+1

**Comment by rambohe-ch** [comment]
@all I think we can accept @SataQiu as OpenYurt community reviewer now.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
