### PR TITLE
refactor(yurt-iot-dock): temporarily remove v3 client to deal with code duplication

### PR DESCRIPTION
**Pull request by LavenderQAQ**
#### What type of PR is this?
/kind enhancement
/sig iot

#### What this PR does / why we need it:
For this pr, the client implementations of the yurt iot-dock of v2 and v3 are merged. Currently, the only difference between v2 and v3 clients is the api request path, which leads to a lot of code redundancy, so we won't separate them for now in 1.4. In 1.5 we will consider splitting them and bringing a MessageBus-based client implementation to v3.
Refer: https://github.com/openyurtio/openyurt/pull/1680

#### Special notes for your reviewer:

/assign @rambohe-ch @wangxye

### CODE REVIEW

**Comment by LavenderQAQ** [comment]
Hold on, there are some problems with introducing packages.

**Review by wangxye — APPROVED** [review]

**Comment by rambohe-ch** [comment]
@LavenderQAQ please fix the conflicting files.

**Comment by LavenderQAQ** [comment]
@rambohe-ch done.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
