### PR TITLE
Fix: yurt-iot-dock crashes when setting the device properties (#1872)

### LINKED ISSUE #1872: [BUG] yurt-iot-dock crashes when setting the device properties
**What happened**:

The yurt-iot-dock will crash when device controller sets the device properties.

**What you expected to happen**:

Device controller in yurt-iot-dock sets the device properties and updates the device status successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Create a device with properties in its spec like:

```yaml
spec:
  adminState: UNLOCKED
  deviceProperties:
    power:
      desiredValue: "true"
      name: power
      putURL: http://edgex-core-command:59882/api/v2/device/name/waterheater/power
    target:
      desiredValue: "40.9"
      name: target
      putURL: http://edgex-core-command:59882/api/v2/device/name/waterheater/target
```

**Anything else we need to know?**:

This piece of code has problem: https://github.com/openyurtio/openyurt/blob/v1.4.0/pkg/yurtiotdock/controllers/device_controller.go#L281-L297

```go
		if actualProperty == nil || desiredProperty.DesiredValue != actualProperty.ActualValue {
			klog.V(4).Infof("DeviceName: %s, the desired value and the actual value are different, desired: %s, actual: %s",
				d.GetName(), desiredProperty.DesiredValue, actualProperty.ActualValue)
			if err := r.deviceCli.UpdatePropertyState(context.TODO(), propertyName, d, clients.UpdateOptions{}); err != nil {
				klog.ErrorS(err, "failed to update property", "DeviceName", d.GetName(), "propertyName", propertyName)
				failedPropertyNames = append(failedPropertyNames, propertyName)
				continue
			}

			klog.V(4).Infof("DeviceName: %s, successfully set the property %s to desired value", d.GetName(), propertyName)
			newActualProperty := iotv1alpha1.ActualPropertyState{
				Name:        propertyName,
				GetURL:      actualProperty.GetURL,
				ActualValue: desiredProperty.DesiredValue,
			}
			newDeviceStatus.DeviceProperties[propertyName] = newActualProperty
		}
```

`actualProperty` maybe nil

**Environment**:
- OpenYurt version: v1.4.0

/kind bug

### PR DESCRIPTION
**Pull request by crazytaxii**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

yurt-iot-dock will crash when device controller reconciles the device properties

#### Which issue(s) this PR fixes:
Fixes #1872

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@LavenderQAQ @zyjhtangtang PTAL

**Review by LavenderQAQ — COMMENTED** [review]
/lgtm

**Comment by LavenderQAQ** [comment]
@wangxye I think this pr could be merged. You're more familiar with this part, please help me with the final review. If there are no questions, I'll merge it.

**Review by LavenderQAQ — APPROVED** [review]

**Pull request merged**
