### PR TITLE
feat: add e2e test case for daemonset pod updater controller

### LINKED ISSUE #1476: [feature request]add e2e test case for daemonset pod updater controller
**What would you like to be added**:
add e2e test case for daemonset pod updater controller

**Why is this needed**:
improve the e2e test coverage

**others**
/kind feature

### PR DESCRIPTION
**Pull request by y-ykcir**
#### Which issue(s) this PR fixes:

Fixes #1476 

#### Does this PR introduce a user-facing change?

```release-note

```

#### other Note

has written e2e tests for the auto upgrade model and ota upgrade model of the daemonset pod updater respectively

### CODE REVIEW

**Comment by y-ykcir** [comment]
need to figure out the reason for autonomy test failure. It may be due to the use of the `docker network disconnect/connect kind openyurt-e2e-test-worker2` in the daemonset pod updater test

**Comment by rambohe-ch** [comment]
@xavier-hou PTAL

**Comment by xavier-hou** [comment]
image

It seems that in `Kind` env, `docker diconnect` will effect flannel NIC. And this leds to the failure of autonomy e2e test.

**Comment by y-ykcir** [comment]
@xavier-hou Has fixed the automony test according to the suggestions. PTAL.

**Comment by xavier-hou** [comment]
@rambohe-ch  LGTM

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
