### PR TITLE
Add gnunu (shaoqiang.chen@intel.com) as a maintainer of OpenYurt.

### PR DESCRIPTION
**Pull request by gnunu**
## GitHub Username
@gnunu

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch

## Requirements
* [x]  I have joined in the community [Dingding] and [WeChat]
* [x]  I often attend Openyurt Community Week
* [x]  I have reviewed the [community membership docs]
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
* [x]  I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
* [x]  I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions
* PRs reviewed / authored:
  [Proposal: OpenYurt Convertor Operator for converting K8S to OpenYurt](https://github.com/openyurtio/openyurt/pull/389)
  [Proposal: add dynamic load balancer support for openyurt](https://github.com/openyurtio/openyurt/pull/528)
  [Proposal: add ingress feature support to nodepool](https://github.com/openyurtio/openyurt/pull/373)
* Issues :
  [[feature request]Should an Operator be good to turn vanilla k8s cluster to OpenYurt one?](https://github.com/openyurtio/openyurt/issues/328)

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@gnunu It's my honor to support you to apply maintainer of OpenYurt community. agree +1
and considerations as following:
1. Be responsible or participate for YurtCluster, Ingress-Controller, Dynamic LB, Edge-AI etc. and familiar with OpenYurt.
2. Very active in community discussions, like issue, meeting etc.
3. Have made a lot of contributions to OpenYurt community.

**Comment by rambohe-ch** [comment]
@Fei-Guo @yixingjia @charleszheng44

**Comment by Fei-Guo** [comment]
+1

**Comment by charleszheng44** [comment]
+1

**Pull request merged**
