### PR TITLE
fix spelling mistakes

### PR DESCRIPTION
**Pull request by JameKeal**
#### What this PR does / why we need it:
some spelling mistakes, some little detail, it doesn't matter

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by Congrool** [comment]
looks good. I cannot find any reason for this e2e-tests error. Maybe need a retest.
Could you please retest it? @rambohe-ch

**Comment by Congrool** [comment]
Thanks.
/lgtm

**Review by rambohe-ch — APPROVED** [review]

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
