### PR TITLE
bugfix: non resource handle miss for coredns

### PR DESCRIPTION
**Pull request by rambohe-ch**
/kind bug

#### What this PR does / why we need it:
Like coredns component will post non resource request to kube-apiserver through yurthub, but yurthub can not handle non resource request when cloud-edge line off, so coredns can not recover when cloud-edge disconnected.

this pull request is used for solving the above problem.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@Congrool @Sodawyx PTAL

**Comment by Congrool** [comment]
What's the reason that cause CoreDNS unable to restart when cloud-edge disconnect? 

I can find two main changes in this pr:
1. wrap https proxy
2. add `Content-Type: application/json` in header

Are these all we need to enable the CoreDNS to restart when offline?

**Comment by rambohe-ch** [comment]
> What's the reason that cause CoreDNS unable to restart when cloud-edge disconnect?
> 
> I can find two main changes in this pr:
> 
> 1. wrap https proxy
> 2. add `Content-Type: application/json` in header
> 
> Are these all we need to enable the CoreDNS to restart when offline?

@Congrool Yes, the main reason is that https proxy is not wrapped by non resource handler.

**Review by Congrool — COMMENTED** [review]
/lgtm

**Pull request merged**
