### PR TITLE
feat: reclaim device, deviceprofile and deviceservice before exiting YurtIoTDock 

### LINKED ISSUE #1626: [feature request]  Reclaim device, deviceprofile and deviceservice before exiting YurtIoTDock
**What would you like to be added**:
When YurtIoTDock receives the exit signal, it needs to reclaim device, deviceprofile, and deviceservice.

**Why is this needed**:
Clean up unwanted cr for users.

**others**
/kind feature

### PR DESCRIPTION
**Pull request by wangxye**
#### What type of PR is this?
/kind feature
/sig iot

#### What this PR does / why we need it:
When YurtIoTDock receives the exit signal, it needs to reclaim device, deviceprofile, and deviceservice.
Clean up unwanted cr for users.

#### Which issue(s) this PR fixes:
Fixes #1626 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by LavenderQAQ — CHANGES_REQUESTED** [review]
I tried it on my own cluster and still couldn't seem to destroy the crd on exit.
```shell
kubectl get po
NAME                            READY   STATUS    RESTARTS   AGE
yurt-manager-5b8b997644-g8hhx   1/1     Running   0          6m44s
```

```shell
kubectl get device
NAME                                    NODEPOOL   SYNCED   AGE
beijing-random-binary-device            beijing    true     64s
beijing-random-boolean-device           beijing    true     64s
beijing-random-float-device             beijing    true     64s
beijing-random-integer-device           beijing    true     64s
beijing-random-unsignedinteger-device   beijing    true     64s
beijing-sample-image                    beijing    true     64s
beijing-sample-json                     beijing    true     64s
beijing-sample-numeric                  beijing    true     64s
...
```

**Comment by LavenderQAQ** [comment]
@wangxye Sorry, it's the problem with my local shell workflow. The pr test should be fine.

**Review by LavenderQAQ — APPROVED** [review]
/lgtm

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
