### PR TITLE
Remove docs to openyurt/openyurt.io/docs

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

/kind documentation

#### What this PR does / why we need it:
Unify the location of docs.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/assign @rambohe-ch 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@lonelyCZ how about update the README file in this pull request?

**Comment by lonelyCZ** [comment]
The link appears to have been modified

https://github.com/openyurtio/openyurt#tutorials

**Comment by rambohe-ch** [comment]
> The link appears to have been modified
> 
> https://github.com/openyurtio/openyurt#tutorials

ok, i got it.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
