### PR TITLE
fix coredns cannot get /apis/discovery.k8s.io/v1 if cluster does not contain such resource

### PR DESCRIPTION
**Pull request by Congrool**
Signed-off-by: Congrool <chpzhangyifei@zju.edu.cn>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

If we use cordns of a high version (e.g. 1.8) but with a k8s cluster of low version (e.g. 1.20), the coredns cannot list/watch endpointslice/v1beta1, because it cannot discover the supported resource version through "GET /apis/discovery.k8s.io/v1" and "GET /apis/discovery.k8s.io/v1beta1".

The reason causing such problem is that yurthub nonresource handler will return http.StatusOK even the APIServer does not contain such resource. It will cause the coredns continuously "GET /apis/discovery.k8s.io/v1" which blocks the list/watch making it unavailable.

```go
func writeErrResponse(path string, err error, w http.ResponseWriter) {
	klog.Errorf("failed to handle %s non resource request, %v", path, err)
	status := responsewriters.ErrorToAPIStatus(err)
	output, err := json.Marshal(status)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeRawJSON(output, w)
}

func writeRawJSON(output []byte, w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(output)
}
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by Congrool** [comment]
Fix what we don't solve in #1144.  FYI @LaurenceLiZhixin.

BTW, an additional RBAC setting should be set to make it work. We should authorize yurthub to list/watch endpointslice. But it seems we do not need to modify the RBAC for coredns 1.8 in k8s 1.22. I don't know the reason.

**Review by rambohe-ch — APPROVED** [review]

**Comment by Congrool** [comment]
/hold

need to fix unit test

**Comment by LaurenceLiZhixin** [comment]
LGTM

**Pull request merged**
