### PR TITLE
add yurtadm to install/uninstall staticpod

### LINKED ISSUE #1472: [feature request]support install/uninstall static pods on nodes
**What would you like to be added**:
As we known, we have added a new CRD named `YurtStaticSet` to define static pod template and static pod upgrade strategy. but
user should places or remove static pod yaml on the node manually when he wants to install/uninstall specified static pod.

At the same time, `yurtadm join` command is installing yurthub static pod on nodes based on the yurthub YurtStaticSet.
so we want to add the following features to support install/uninstall static pods except yurthub.
1. add `--static-pods={yss1.ns/yss1.name, yss2.ns/yss2.name}` parameter for `yurtadm join` command, so user can installs these specified static pods on this node when joining node by `yurtadm join` command.
2. add  new commands for installing or uninstalling specified static pods after node had been joined in the cluster, as follows:
   - yurtadm staticpods install {yss1.ns/yss1.name, yss2.ns/yss2.name}
   - yurtadm staticpods uninstall {yss1.ns/yss1.name, yss2.ns/yss2.name}

and all these features should exclude yurthub static pod.

**Why is this needed**:
It is very hard for user to install/uninstall static pods on node manually, and we should install/uninstall static pods based on YurtStaticSet resource. so we need add the above features.

**others**
/kind feature

### PR DESCRIPTION
**Pull request by JameKeal**
/kind feature

#### What this PR does / why we need it:

It is very hard for user to install/uninstall static pods on node manually, and we should install/uninstall static pods based on YurtStaticSet resource. so we need add the above features.

#### Which issue(s) this PR fixes:

Fixes #1472 

#### Special notes for your reviewer:

/assign @rambohe-ch 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@YTGhost PTAL

**Comment by YTGhost** [comment]
@JameKeal How about make a pull request to update yurtadm docs in the homepage website?

**Comment by JameKeal** [comment]
> @JameKeal How about make a pull request to update yurtadm docs in the homepage website?

OK, I'll take a time to update it.

**Review by YTGhost — COMMENTED** [review]
/lgtm

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
