### PR TITLE
bump controller-gen to v0.13.0

### PR DESCRIPTION
**Pull request by Congrool**
#### What this PR does / why we need it:

Since we align the openyurt with kubernetes 1.28 in #2047, we should also bump the `controller-gen` to a newer version to avoid compatibility problem whose current version is v0.7.0 which is a bit stale.

`controller-gen` help us automatically generate code for CRDs. We've encountered the situation that the automatic generation cannot be done in release action.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by Congrool** [comment]
@rambohe-ch PTAL

Not sure if this can make the github release workflow run successfully, at least it works around at my host.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
