### PR TITLE
add DeleteYurthubSetting to revert

### LINKED ISSUE #489: [feature request]  DeployYurthubSetting, not delete when revert
https://github.com/openyurtio/openyurt/blob/797c43d730a11a6cd9bd491f3d3838917e2a49cb/pkg/yurtctl/cmd/convert/convert.go#L382
`yurtctl convert `: run function DeployYurthubSetting , create `yurt-hub ClusterRole ClusterRoleBinding` 

Howevert, `yurtctl revert` won't delete them.

### PR DESCRIPTION
**Pull request by adamzhoul**
#### What this PR does / why we need it:
clean all resource, when do revert

#### Which issue(s) this PR fixes:

Fixes #489

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@adamzhoul Another resource named yurt-hub-cfg confgmap has been added for yurthub, how about add create/delete yurt-hub-cfg configmap for yurthub?

The definition of yurt-hub-cfg configmap is here: https://github.com/openyurtio/openyurt/blob/master/config/setup/yurthub-cfg.yaml#L42-L48

**Comment by adamzhoul** [comment]
is this using now？ I can't find any place using this yet.
besides： do you mean put  clusterrolebinding 、clusterrole configs into configmap , use operator to create or delete resource?

**Comment by rambohe-ch** [comment]
> is this using now？ I can't find any place using this yet.
> besides： do you mean put clusterrolebinding 、clusterrole configs into configmap , use operator to create or delete resource?

@adamzhoul This configmap is used by yurthub. so we need to add creation of this configmap in https://github.com/openyurtio/openyurt/blob/master/pkg/yurtctl/util/kubernetes/apply_addons.go#L206-L218. not add clusterrolebinding 、clusterrole configs into configmap.

**Comment by adamzhoul** [comment]
now I understand. 
I will put `create` in :

https://github.com/openyurtio/openyurt/blob/32df8c28893ce4d4c0dc9d3c73757cc9f72f74f0/pkg/yurtctl/util/kubernetes/apply_addons.go#L206-L218

and put `delete` in the new function `DeleteYurthubSetting`.

**Pull request merged**
