### PR TITLE
improve error message

### LINKED ISSUE #1781: [feature request] improve error message in order to up efficiency.
**What would you like to be added**:
When unit tests failed, we need to search the keyword `fail` to find out the failed cases, but there are many error messages that include keyword `fail`(such as in the following image), this will affect our efficiency in finding failed cases.

image

so i think we can improve the error messages, this means change word `fail` to `couldn't` as following:

```
failed to update the DynamicRESTMapper failed to update cached dynamic RESTMapper, path does not exist --> could not update the DynamicRESTMapper failed to update cached dynamic RESTMapper, path does not exist
```

**others**
/kind feature

### PR DESCRIPTION
**Pull request by dzcvxe**
What type of PR is this?
> /kind good-first-issue
> /kind feature

What this PR does / why we need it:
When unit tests failed, we need to search the keyword fail to find out the failed cases, but there are many error messages that include keyword fail, this will affect our efficiency in finding failed cases.

Which issue(s) this PR fixes:
Fixes #1781

### CODE REVIEW

**Review by rambohe-ch — APPROVED** [review]

**Comment by rambohe-ch** [comment]
@dzcvxe Thank for very much, it is a good job.

**Review by YTGhost — APPROVED** [review]
/lgtm

**Pull request merged**
