### PR TITLE
openyurt chart and sync to repo

### PR DESCRIPTION
**Pull request by huiwq1990**
/kind feature
> /kind question
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@huiwq1990 Thank you for posting pull request for OpenYurt charts. 

how about rename `openyurt-cloud-controller` to `openyurt`(repo name)? so it's more readable for end user when using openyurt-helm repo.

**Comment by huiwq1990** [comment]
> @huiwq1990 Thank you for posting pull request for OpenYurt charts.
> 
> how about rename `openyurt-cloud-controller` to `openyurt`(repo name)? so it's more readable for end user when using openyurt-helm repo.

fixed

**Comment by rambohe-ch** [comment]
> > @huiwq1990 Thank you for posting pull request for OpenYurt charts.
> > how about rename `openyurt-cloud-controller` to `openyurt`(repo name)? so it's more readable for end user when using openyurt-helm repo.
> 
> fixed

@huiwq1990 `hack/lib/sync-charts.sh` file should also be updated.

**Review by rambohe-ch — APPROVED** [review]

**Comment by huiwq1990** [comment]
@rambohe-ch github workflow failed, as https://github.com/openyurtio/openyurt/runs/7294638000?check_suite_focus=true. We need create secret for `openyurt`, just like: 
image
and create deploy key for `openyurt-helm`, like 
image

**Comment by rambohe-ch** [comment]
Fixes #824

**Pull request merged**
