### PR TITLE
fix:readme slack url

### PR DESCRIPTION
**Pull request by karthik507**
Readme file update with new slack url , kindly update the new url.

### CODE REVIEW

**Comment by YTGhost** [comment]
@karthik507 The revised link is not the same as the one @rambohe-ch provided before?

**Comment by karthik507** [comment]
> @karthik507 The revised link is not the same as the one @rambohe-ch provided before?

@YTGhost the link which you gave was working url :https://join.slack.com/t/openyurt/shared_invite/zt-2bptiyzuv-oDDlfdLwS0AuxSyD4cq4eA  and @rambohe-ch url was different and that was also working ,i updated the url which you gave.

**Comment by YTGhost** [comment]
> > @karthik507 The revised link is not the same as the one @rambohe-ch provided before?
> 
> @YTGhost the link which you gave was working url :https://join.slack.com/t/openyurt/shared_invite/zt-2bptiyzuv-oDDlfdLwS0AuxSyD4cq4eA and @rambohe-ch url was different and that was also working ,i updated the url which you gave.

The URL I provided appears to expire, but @rambohe-ch gave does not. Please change it to the one he provided.

**Comment by karthik507** [comment]
> > > @karthik507 The revised link is not the same as the one @rambohe-ch provided before?
> > 
> > 
> > @YTGhost the link which you gave was working url :https://join.slack.com/t/openyurt/shared_invite/zt-2bptiyzuv-oDDlfdLwS0AuxSyD4cq4eA and @rambohe-ch url was different and that was also working ,i updated the url which you gave.
> 
> The URL I provided appears to expire, but @rambohe-ch gave does not. Please change it to the one he provided.

@YTGhost  okay

**Review by rambohe-ch — APPROVED** [review]

**Comment by rambohe-ch** [comment]
Fixes #1944

**Pull request merged**
