### PR TITLE
fix yurthub memory leak

### PR DESCRIPTION
**Pull request by JameKeal**
/kind bug

#### What this PR does / why we need it:
When yurthub connect with pool-coordinator etcd failed, and keep try again, the goroutine of grpc is increase all the while, and memory of yurthub also increase, and kubelet will restart it when is happen OOM.
0efec082db7f88f00fa4934ba4ba366

e50ee49fda9b174b93760f01bf9c10e

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@Congrool PTAL

**Review by Congrool — COMMENTED** [review]
/lgtm

Thanks!

**Review by Congrool — COMMENTED** [review]
/lgtm

Thanks!

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
