### PR TITLE
fix format err in pkg/webhook/builder/webhook.go

### PR DESCRIPTION
**Pull request by yeqiugt**
#### What this PR does / why we need it:
Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context.

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

### CODE REVIEW

**Review by luckymrwang — APPROVED** [review]
/lgtm

**Comment by rambohe-ch** [comment]
@yeqiugt Very appreciate for your pull request and welcome you to contribute OpenYurt community.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
