### PR TITLE
Add adamzhoul as reviewer of openYurt

### PR DESCRIPTION
**Pull request by adamzhoul**
## GitHub Username
@adamzhoul 

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch

## Requirements

- [x]  I have joined in the community [Dingding] and [WeChat]
- [x]  I often attend Openyurt Community Week
- [x]  I have reviewed the [community membership docs]
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x]  I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x]  I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions

- PRs reviewed/authored:
#516
#506
#500
#494
#492
#490
#473
#463
#459

- Issues :
#547
#546
#545
#544
#505
#502
#499
#498
#489
#488
#486
#485
#462
#461
#460

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@adamzhoul welcome you to apply reviewer of OpenYurt. agree +1

**Comment by Peeknut** [comment]
agree +1

**Review by qclc — COMMENTED** [review]
agree+1

**Comment by SataQiu** [comment]
Welcome @adamzhoul 

+1 from me

**Comment by Fei-Guo** [comment]
+1

**Comment by rambohe-ch** [comment]
@adamzhoul Congratulations to you as reviewer, and you can check the reviewer's responsibilities and privileges here: https://github.com/openyurtio/community/blob/main/community-membership.md#reviewer

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
