### PR TITLE
yurt express: openyurt data transmission system proposal

### PR DESCRIPTION
**Pull request by qsfang**
#### What type of PR is this?
 /kind feature

#### What this PR does / why we need it:
Add proposal for supporting edge data tunnel with openyurt

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@qsfang please fix the markdown lint errors.

**Comment by qsfang** [comment]
edge data tunnel will be a new project under openyurt, and it needs a new name.
ChatGPT offers me some options, and i prefer "yurtward", which means directed or moving towards a yurt. 

---
"Yurtward" is an adverb that describes a direction or movement towards a yurt. For example, "They walked yurtward, eager to reach their cozy yurt in the campsite." It indicates the orientation or destination in relation to a yurt.

**Comment by qsfang** [comment]
> @qsfang please fix the markdown lint errors.

@rambohe-ch markdown lint issues are fixed, need review

**Comment by qsfang** [comment]
@rambohe-ch  pls review, optimized according to weekly meeting discussion
Project name  rename to "yurt-express"
--- 
 Additionally, add YurtExpressChannel CRD to define user channel, and original configmap channel definition is deprecated.
 For user configuration simplicity and future cloud-edge, edge-edge data transition extension implementation

**Comment by rambohe-ch** [comment]
> @rambohe-ch pls review, optimized according to weekly meeting discussion Project name rename to "yurt-express" Additionally, add YurtExpressChannel CRD to define user channel, and original configmap channel definition is deprecated.For user configuration simplicity and future cloud-edge, edge-edge data transition extension implementation

@qsfang It seems that YurtExpressChannel CRD is a good idea for user to configure the settings of transmit tunnel.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
