### PR TITLE
fix: raven-controller-manager supports calico

### LINKED ISSUE #1434: unable to get podCIDR，unable to list calico blockaffinity
E0508 02:05:48.362747       1 gateway_controller.go:180] "unable to get podCIDR" err="ravenl3-gateway: unable to list calico blockaffinity: no kind is registered for the type v3.BlockAffinityList in scheme \"pkg/runtime/scheme.go:100\"" 
E0508 02:05:48.362782       1 controller.go:317] setup/controller/ravenl3-gateway "msg"="Reconciler error" "error"="ravenl3-gateway: unable to list calico blockaffinity: no kind is registered for the type v3.BlockAffinityList in scheme \"pkg/runtime/scheme.go:100\"" "name"="enterprise-9999" "namespace"="" 

calico: v3.20.0
k8s: v1.23.6

### PR DESCRIPTION
**Pull request by luckymrwang**
/kind bug

#### Which issue(s) this PR fixes:

Fixes #1434

#### Special notes for your reviewer:

/assign @njucjc 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by njucjc** [comment]
Please fix CI error first

**Comment by luckymrwang** [comment]
> Please fix CI error first

CI has been fixed.

**Comment by luckymrwang** [comment]
> Please fix CI error first

CI has been fixed.

**Comment by njucjc** [comment]
LGTM

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
