### PR TITLE
add edge-pod-network doc

### PR DESCRIPTION
**Pull request by wenjun93**
### Ⅰ. Describe what this PR does
add doc for edge pod network.

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@wenjun93 Thank you for adding the doc of edge pod network. and how about add the following the contents:
1.  the background of the pod network autonomy 
2. the problems for making sure pod network autonomy

and then explain the solutions of problems. 
by the way, It is easier to understand if an arch pic of edge pod network can be added.

**Comment by wenjun93** [comment]
> @wenjun93 Thank you for adding the doc of edge pod network. and how about add the following the contents:
> 
> 1. the background of the pod network autonomy
> 2. the problems for making sure pod network autonomy
> 
> and then explain the solutions of problems.
> by the way, It is easier to understand if an arch pic of edge pod network can be added.

updated

**Comment by Fei-Guo** [comment]
1) Please fix the lint errors
2) Is this possible to show the code diff if the patch is simple?  

Especially the local IPAM plugin change is requested by many users many times. It will be nice to provide more details so that user can DIY.

**Comment by wenjun93** [comment]
@Fei-Guo The doc proposed 

> 1. Please fix the lint errors
> 2. Is this possible to show the code diff if the patch is simple?
> 
> Especially the local IPAM plugin change is requested by many users many times. It will be nice to provide more details so that user can DIY.

the patch is not simply a few lines of code change, we might discuss it.

**Review by Fei-Guo — APPROVED** [review]

**Pull request merged**
