### PR TITLE
fix: update alpine 3.17 to 3.18

### PR DESCRIPTION
**Pull request by fengshunli**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@fengshunli Very appreciate for your pull request. would you like to explain the reason why update alpine 3.17 to 3.18?

**Comment by fengshunli** [comment]
> @fengshunli Very appreciate for your pull request. would you like to explain the reason why update alpine 3.17 to 3.18?

The mirror version of 3.17 has stopped maintenance, and the high-risk vulnerabilities that have appeared are no longer fixed

**Comment by rambohe-ch** [comment]
> > @fengshunli Very appreciate for your pull request. would you like to explain the reason why update alpine 3.17 to 3.18?
> 
> The mirror version of 3.17 has stopped maintenance, and the high-risk vulnerabilities that have appeared are no longer fixed

@fengshunli Thanks for your response, would you like to upload the info link that alpine 3.17 maintenance has been stopped?

**Comment by fengshunli** [comment]
> 

@rambohe-ch There are loopholes in version 3.17, and the official version is no longer updated. For details, please refer to https://www.alpinelinux.org/

**Comment by fengshunli** [comment]
> > 
> 
> @rambohe-ch There are loopholes in version 3.17, and the official version is no longer updated. For details, please refer to https://www.alpinelinux.org/

image
WDYT @rambohe-ch

**Pull request closed without merging**
