### PR TITLE
cleanup: io/ioutil

### PR DESCRIPTION
**Pull request by cndoit18**
Signed-off-by: cndoit18 <cndoit18@outlook.com>

#### What type of PR is this?

/kind good-first-issue

#### What this PR does / why we need it:

Please see https://golang.org/doc/go1.16#ioutil

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@cndoit18 Very appreciate for your work to upgrade `io/ioutil`.  and based on https://go.dev/doc/go1.16#ioutil introduction, we need to replace `io/ioutil` with `io` or `os` library.

**Comment by cndoit18** [comment]
> @cndoit18 Very appreciate for your work to upgrade `io/ioutil`. and based on https://go.dev/doc/go1.16#ioutil introduction, we need to replace `io/ioutil` with `io` or `os` library.

Hi, Do I need to do anything else?

**Comment by rambohe-ch** [comment]
> > @cndoit18 Very appreciate for your work to upgrade `io/ioutil`. and based on https://go.dev/doc/go1.16#ioutil introduction, we need to replace `io/ioutil` with `io` or `os` library.
> 
> Hi, Do I need to do anything else?

@cndoit18 no, and i will take a review and give you feedback.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
