### PR TITLE
add some unit tests for yurt tunnel

### LINKED ISSUE #416: [yurt tunnel]welcome add unit testcases for yurt-tunnel components.
**What would you like to be added**:
To add unit test cases for yurt-tunnel is a good way to understand specified components.
welcome to add test case for any small or big functions.

**Why is this needed**:
improve the reliability of yurt-tunnel.

**others**
/kind feature

### PR DESCRIPTION
**Pull request by YRXING**
#### What this PR does / why we need it:
improve the reliability of yurt-tunnel.

#### Which issue(s) this PR fixes:

Fixes #416  

#### Does this PR introduce a user-facing change?
NONE

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@YRXING Please add the license header for new files. btw: fix the lint errors and unit-test failed cases.

**Comment by rambohe-ch** [comment]
@YRXING please merge these six commits into one commit.

image

**Comment by rambohe-ch** [comment]
@YRXING please fix the following errors.
image

**Comment by rambohe-ch** [comment]
@YRXING please merge all commits into one commit.
image

**Comment by YRXING** [comment]
I have format the go file but golangci-lint still filed.

**Comment by YRXING** [comment]
> @YRXING please fix the following errors.
> image

I have format the project but golangci-lint still failed.

**Comment by rambohe-ch** [comment]
> > @YRXING please fix the following errors.
> > image
> 
> I have format the project but golangci-lint still failed.

@YRXING On my local desktop, the golangci-lint errors as following:
```
helinbodeMacBook-Pro:openyurt helinbo$ golangci-lint run --out-format=github-actions --disable-all  -E deadcode -E gofmt -E goimports -E ineffassign -E misspell -E vet --timeout=15m
::error file=pkg/yurttunnel/dns/util.go,line=116::File is not `gofmt`-ed with `-s` (gofmt)
::error file=pkg/profile/profile_test.go,line=20::File is not `goimports`-ed (goimports)
::error file=pkg/yurttunnel/handlerwrapper/tracerequest/tracereq_test.go,line=20::File is not `goimports`-ed (goimports)
::error file=pkg/yurttunnel/dns/util_test.go,line=20::File is not `goimports`-ed (goimports)
```

**Comment by rambohe-ch** [comment]
> > @YRXING please fix the following errors.
> > image
> 
> I have format the project but golangci-lint still failed.

@YRXING you need to install goimports command and reformat the above code files. and if you use goland to edit golang code, you can right click above files and select `Go Tools` --> `Goimports File` to format files.

**Comment by rambohe-ch** [comment]
@YRXING Would you like to apply OpenYurt community member, and you can add me as sponsor. apply example is here: https://github.com/openyurtio/community/issues/24

**Pull request merged**
