### PR TITLE
servant preflight jobs take care of all necessary images pulling in c…

### PR DESCRIPTION
**Pull request by gnunu**
…ase of using private image hub

Signed-off-by: nunu <shaoqiang.chen@intel.com>

/kind bug
> /kind documentation
> /kind enhancement
> /kind good-first-issue
> /kind feature
> /kind question
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage

/kind bug

#### What this PR does / why we need it:
now preflight just considers yuthub image, for using private hub, all images should be taken care of.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/assign @rambohe-ch 
/assign @Peeknut 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@gnunu Preflight check of node servant is used for edge nodes, so only yurthub and yurt-tunnel-agent images have been checked. i think it's reasonable.

**Comment by gnunu** [comment]
pkg/node-servant/constant.go:

**Comment by gnunu** [comment]
> @gnunu Preflight check of node servant is used for edge nodes, so only yurthub and yurt-tunnel-agent images have been checked. i think it's reasonable.

pkg/node-servant/constant.go:
```
- "/usr/local/bin/entry.sh preflight-convert {{if .ignore_preflight_errors}}--ignore-preflight-errors {{.ignore_preflight_errors}} {{end}}"
```
Currently preflight-convert dose not process the arguments from yurtctl command line, including the images specified for yurthub, tunnel-agent, etc. For this command to correctly pull the images from specified position, the changes made is necessary.

I think preflight check is a good feature, like "kubeadm config imagepull".

It's indeed we don't need to pull images execept yurthub and tunnel-agent for edge nodes. That can be improved.

**Comment by gnunu** [comment]
use env IS_CLOUD_NODE (default null) to seperate cloud node and worker node. so for worker node, only yurthub and yurttunel (if necessary) images will be pulled.

next step is to add this env if necessary.

**Comment by rambohe-ch** [comment]
@gnunu please fix the golangci lint error and conflicting files.

**Comment by rambohe-ch** [comment]
@gnunu as you known, `yurtctl covert/revert` command had been removed, so i will close this pull request.

**Pull request closed without merging**
